### ISSUE TITLE
React website redirection.

### ISSUE THREAD

**Issue by Amtr4x** [devchallenges-io/join-our-newsletter#2]
I consider will be a good idea to replace in the *readme templates* the link to the Reactjs website. The official website is at https://react.dev , it is not a critical bug or something to alarm us but for some newbies it can lead in typosquatting if they try to remember what is the link to the React website. When you enter at reactjs.org you get a 300 code,  but nobody know if some day this domain is victim of a takeover and leads to disaster in our community.

**Comment by ghost** [comment]
It has already been fixed as reactjs.org redirects to react.dev
